modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="trumpcraft"
version="6.0.12.0"
displayName="Trumpcraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="DereC_"
description='''
We'll make Minecraft great again
'''

[[dependencies.trumpcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



